version: 1.0.{build}
before_build:
  - nuget restore
build:
  project: Toxiproxy.Net.sln
  verbosity: minimal

after_build:
  - nuget pack Toxiproxy.Net.nuspec

after_test: 
  - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[Toxiproxy*]* -[Toxiproxy.Net.Tests]*" -target:"packages\xunit.runner.console.2.0.0\tools\xunit.console.x86.exe" -targetargs:"Toxiproxy.Net.Tests\bin\debug\Toxiproxy.Net.Tests.dll -appveyor -noshadow" -output:coverage.xml

artifacts:
  - path: '*.nupkg'
